version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - run: 
          name: Zainstaluj zależności
          command: make deps
      - run: 
          name: Uruchom Linter
          command: make lint
      - run: 
          name: Uruchom Testy
          command: make test

workflows:
  basic:
    jobs:
      - build-and-test